from . import opex_membership_category
from . import opex_membership_subcategory
from . import opex_certification
from . import res_partner
from . import res_users
from . import opex_membership_file
from . import opex_membership_document
from . import opex_membership_correction
from . import opex_subscription
from . import opex_payment
from . import opex_cluster_news
from . import opex_cluster_training
from . import opex_cluster_event
from . import opex_cluster_event_registration
from . import account_move
